image: python:3.11

stages:
  - lint


flake8:
  stage: lint
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements/test.txt
    - flake8 lyceum

black:
  stage: lint
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements/dev.txt
    - black --check lyceum