stages:
  - lint
  - test

flake8:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  before_script:
    - pip install --upgrade pip  
    - pip install -r requirements/test.txt
  script:
    - flake8 --verbose lyceum

black:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check lyceum

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements/test.txt
    - cd lyceum
    - python manage.py migrate
  script:
    - python manage.py test